# YAMCS-ROS Bridge Configuration

yamcs:
  url: "localhost:8090"
  instance: "dragoman"
  processor: "realtime"

bridges:

  # Lunar Exploration space telemetry packet
  - ros_message_type: "dragoman_sample_msgs/msg/LunarExplorationTelemetryPacket"
    ros_topic: "/yamcs/lunar_exploration_space"
    yamcs_packet_name: "/LunarExploration/LunarExplorationTelemetryPacket"

  # Lunar Exploration ground telemetry packet
  - ros_message_type: "dragoman_sample_msgs/msg/GroundTelemetryPacket"
    ros_topic: "/yamcs/lunar_exploration_ground"
    yamcs_packet_name: "/LunarExploration/GroundTelemetryPacket"
