# ROS 2 Message: CuriosityTelemetryPacket.msg
# Generated automatically from XTCE file: /dragoman/install/dragoman_sample_xtce/share/dragoman_sample_xtce/xtce/Curiosity.xtce
# Generation Date: 2025-12-08 14:03:54

float32[24] joint_state # arm_01, arm_02, arm_03, arm_04, arm_tools, back_wheel_L, back_wheel_R, front_wheel_L, front_wheel_R, mast_02, mast_cameras, mast_p, middle_wheel_L, middle_wheel_R, suspension_arm_B2_L, suspension_arm_B2_R, suspension_arm_B_L, suspension_arm_B_R, suspension_arm_F_L, suspension_arm_F_R, suspension_steer_B_L, suspension_steer_B_R, suspension_steer_F_L, suspension_steer_F_R
