<?xml version="1.0"?>
<package format="3">
  <name>dragoman_yamcs_project</name>
  <version>0.0.0</version>
  <description>YAMCS integration package for Dragoman project</description>
  <maintainer email="robotics@traclabs.com">TRACLabs Robotics</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>ament_index_cpp</depend>
  <depend>dragoman_generated_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>java</depend>
  <depend>maven</depend>
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
