# YAMCS-ROS Bridge Configuration

yamcs:
  url: "localhost:8090"
  instance: "dragoman"
  processor: "realtime"

bridges:
  # Gateway telemetry packet
  - ros_message_type: "dragoman_sample_msgs/msg/GatewayTelemetryPacket"
    ros_topic: "/yamcs/gateway"
    yamcs_packet_name: "/Gateway/GatewayTelemetryPacket"
